### ISSUE TITLE
Investigate bulk failure

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#201]
https://circleci.com/gh/onyx-platform/onyx/1293

**Comment by lbradstreet** [comment]
So far this looks like a case of a test running slow, input retry, and an overflowed sliding-buffer. It's a bit unlucky for it to have happened with this test compared to the others because it doesn't seem particularly difficult. 

It'd be good if our tests flagged cases where inputs were retried. It's a bit hard to tell if it's something to worry about otherwise.

**Comment by MichaelDrogalis** [comment]
I think I see what's going wrong here. The idea with a bulk function is that it takes the entire collection of segments, and emits those same segments. With the acking model that we're using, only one segment can create one or more segments. We have to skip any acknowledgment at all of the segments in the bulk task and let them pass through to the next task.

**Comment by lbradstreet** [comment]
I think we were passing on every segment as leaves of every segment. I don't think there's anything wrong with the approach we were using, each segment should only have its own leaf (you'll see what I mean in the PR)

**Comment by MichaelDrogalis** [comment]
Merged into master.
