### ISSUE TITLE
Triggers/refinements need to emit log entries

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#314]
These need to be emitted any time state is refined in a destructive way. 

For example, refine-state :discarding, should write out a "discard" log entry, and then on success do the discard. I'm not sure how we're going to do acking here because these events can happen on a timer.

**Comment by MichaelDrogalis** [comment]
I have a partial patch for this at https://github.com/onyx-platform/onyx/commit/83fd25ac58ccec282a2899103a55bb24ca1135ac. Since we can't guarantee any atomicity between the sync function and writing to the log, I opted to sync first, then write to the log. If there's a failure, the sync gets called twice - which seems preferably to a skipped trigger fire. This patch does not address timers. This patch also inflates expired windows with hanging `nil`s - we can easily clean this up on log playback though. Thoughts?

**Comment by MichaelDrogalis** [comment]
Patch is complete with durable timer entries and window playback clean up.

**Comment by lbradstreet** [comment]
373 looks good. Closing
