### ISSUE TITLE
Fix swallowed exceptions caused by timbre pretty printing

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#376]
This caused swallowed exceptions in the past and we have disabled the workaround.

**Comment by MichaelDrogalis** [comment]
Interestingly, the `defmethod` we set up never gets called.

**Comment by MichaelDrogalis** [comment]
I was wrong. Turns out the defmethod *does* get called - but it must perform side effects and print `m`. We were simply returning a string via `pr-str`, so nothing was happening. Also - turns out this method is only for print the text for the `:data` key. Solved it by printing it right on the spot. See #378.

**Comment by lbradstreet** [comment]
Weird that it's only used for the `:data` key. Kinda unexpected. Looks good though.
