### ISSUE TITLE
Ensure that ack-value can never generate zero

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#440]
Up a bit late writing some generative tests for the acking daemon. Caught a problem where the initial ack value was being generated as zero. Ensure that this can never happen, otherwise we're vulnerable to message loss.

**Comment by lbradstreet** [comment]
There is a 1/2^64 = 1/1844674407370960000 chance of generating a 0. This is the same chance of a new ack value generating the same value as an ack and cancelling it out (i.e. the normal chance of message loss).

The reason you're seeing so many of them is that generators are generally biased towards simple values, such as 0. I think that this is affected by the number of samples they generate. Try (gen/sample gen/int) and then adjust the number of samples it generates.

I think we can close this.

**Comment by lbradstreet** [comment]
Oh, because of the fact that it's a probabilistic algorithm and the way gen/int generates biased values, you're going to end up prematurely acking values because of the cancel out issue. I think you can use gen/sized to ensure a better range of values. Alternately you can probably use (gen/return (random-long)). I don't think it'll hurt shrinking because we shouldn't really be shrinking along the ack-val

**Comment by MichaelDrogalis** [comment]
Late night brain is good at being paranoid. :) Thanks for the reminder.
