### ISSUE TITLE
Create versioned docs on onyxplatform.org

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#513]
As discussed with tcrayford.

e.g. http://www.onyxplatform.org/docs/0.8.6, http://www.onyxplatform.org/docs/0.8.7
and http://www.onyxplatform.org/docs/latest
This also applies to the cheat sheet.

**Comment by MichaelDrogalis** [comment]
Done. See http://www.onyxplatform.org/docs/user-guide/0.8.8/concepts.html for an example. Versioned User Guide, API docs, and Cheat Sheet.

We can't do redirects such as `/latest/` easily with Jekyll because it doesn't have a router, and the only gem that GitHub will let you run on Pages gives you file-by-file redirection. I definitely want this, but I don't think its practical right now unless someone has another solution.

**Comment by emidln** [comment]
If there's a Jekyll module that can do it otherwise, could we use CI to run
Jekyll and push it to this branch?

**Comment by MichaelDrogalis** [comment]
@emidln I don't *think* so, because GitHub Pages actually runs `jekyll build` on their own servers. At any rate, I wasn't able to find a Jekyll plugin that does general route redirection. The closest that I believe we can come would be coping every file name into a `latest` dir and using the redirection gem that I mentioned - ick.

It would be really nice if Jekyll gave us a routes file to do this kind of thing in, but I understand that's not what it was built for.
