### ISSUE TITLE
add-task fails for tasks that already have TaskMap schema

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#585]
[This](https://github.com/onyx-platform/onyx/blob/6d838c9d3a70663d0f84dbbd3021acc54393d009/src/onyx/job.clj#L21) will fail if the task-definition already has, say `TaskMap` at `:schema :task-map`, such as with some plugin tasks because `(UniqueTaskMap TaskMap)` will throw an exception like:

```
No implementation of method: :explain of protocol:
#'schema.core/Schema found for class: clojure.lang.LazySeq
```

In larger contexts, such as tests, I wasn't getting quite the same error but it was:

```
java.lang.IllegalArgumentException: No implementation of method: :spec of protocol:
#'schema.core/Schema found for class: clojure.lang.Symbol
```

**Comment by MichaelDrogalis** [comment]
cc @gardnervickers

**Comment by gardnervickers** [comment]
@neverfox The plugin task bundles have been updated to no longer have the explicit merge with TaskMap. As a user, you just supply schema to be merged in. This is necessary because of the way schema merges work with conditional schemas. 

This is the preferred way to add schema checks to your task bundles now.
https://github.com/onyx-platform/onyx-kafka/blob/0.9.x/src/onyx/tasks/kafka.clj#L20-L65

Maybe we should add a note that `UniqueTaskMap` only knows how to merge non-conditional schemas with the TaskMap schema.

**Comment by neverfox** [comment]
@gardnervickers I gathered as much from the fact that onyx-template included its own version of `add-task`. In that case, should the one included with the API be changed or simply removed?

**Comment by gardnervickers** [comment]
@neverfox Yea we're in the middle of re-writing the template. The plan is to drop the version in onyx-template for the one in core. Most of the template is going to be re-written.

**Comment by MichaelDrogalis** [comment]
Changed have been promoted to master. @gardnervickers Should I close this one?
