### ISSUE TITLE
Open an HTTP endpoint for every Peer Group for remote query

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#621]
Every peer group should optionally open an HTTP endpoint for health checks and status reports. This facilitates querying in a pull based manner, which complements the pushed based functionality that we already provide.

**Comment by dignati** [comment]
Exposing what lib-onyx already provides([replica-query](https://github.com/onyx-platform/lib-onyx/blob/master/src/lib_onyx/replica_query.cljc) and [job-query](https://github.com/onyx-platform/lib-onyx/blob/master/src/lib_onyx/job_query.clj)) would probably a good start I think? Or do you have something else in mind?

**Comment by lbradstreet** [comment]
Yep, that's essentially what I'm thinking.

The main problem is that it won't be able to use the lib-onyx subscriber because the peer group manages a replica and need to perform transitions, and we don't want a second log subscriber. This should be relatively easy to work around though, we just need the peer group to update the replica atom used by the HTTP server end point.

It'd be good to have an option to turn it on and off via the peer-config.

**Comment by lbradstreet** [comment]
Done
