### ISSUE TITLE
Maybe don't retry jobs that will always fail?

### ISSUE THREAD

**Issue by jcf** [onyx-platform/onyx#635]
When I start my system I encounter an error because something is misconfigured. When the task can't be started it gets restarted again and again only to fail over and over.

```
clojure.lang.ExceptionInfo: Caught exception inside task lifecycle. Rebooting the task. -> Exception type: clojure.lang.ExceptionInfo. Exception message: :onyx/min-peers must equal :onyx/max-peers and the number of partitions, or :onyx/n-peers must equal number of kafka partitions
```

This fills up my logs, and doesn't really help me solve the underlying issue.

**Comment by lbradstreet** [comment]
You're right. This should be handled differently by the Kafka plugin, which should :kill the job, in handle-exception, on validation exceptions rather than return :restart. We chose to restart by default as some exceptions are transient. Validation exceptions are not and should be killed. I think we can close this issue and reopen it in onyx-kafka, as the fault and logic in deciding when to restart is up to the plugin.
